- prependMsg: ""
- checks:
    - paths: "**/*.*"
      message: |
        ### Please tick the following checkboxes:

        - [ ] the code is tested
        - [ ] files are compressed
        - [ ] files contain no errors
