name: "Hello World"
description: "Greet someone and record the time"
inputs:
  message: # id of input
    description: "posts message to a PR"
    required: true
    default: "World"
runs:
  using: "node20"
  main: "dist/index.js"
