on:
  pull_request:
    branches:
      - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check component dependencies
        uses: ./.github/actions/setup-composite
        id: components-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          settings: |-
            paths: src/components
            message: Detected: changes in **components** folder have been made
            paths: src/utils
            message: Detected: changes in **utils** folder have been made
            paths: *.js
            message: javascript files were touched
