on:
  pull_request:
    branches:
      - main
      - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create a comment action step
        uses: ./
        id: hello
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          message: |
            # Solar System Exploration, 1950s – 1960s
            - [ ] Mercury
            - [x] Venus
            - [x] Earth (Orbit/Moon)
            - [x] Mars
            - [ ] Jupiter
            - [ ] Saturn
