on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          message: "Test message!"
