on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create a comment action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
